name: pulse
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - nvidia::cudatoolkit
  - pytorch::pytorch  
  - pip
  - numpy
  - scipy
  - pip:
    - opencv-python
    - diffusers